apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster
  namespace: argocd
spec:
  generators:
    - clusters: {}

  template:
    metadata:
      name: "{{name}}-app"

    spec:
      project: default

      source:
        repoURL: http://gitea.gitea.svc.cluster.local:3000
        targetRevision: HEAD
        path: apps/{{name}}

      destination:
        server: "{{server}}"
        namespace: dev-app

      syncPolicy:
        automated:
          prune: true
          selfHeal: true