server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argo.dev.local
    paths:
      - /

  extraArgs:
    - --insecure

  service:
    type: ClusterIP

configs:
  params:
    server.insecure: true