service:
  http:
    type: LoadBalancer

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.dev.local
      paths:
        - path: /
          pathType: Prefix

gitea:
  admin:
    username: admin
    password: adminadmin1
    email: admin@local.dev

persistence:
  enabled: false