---
apiVersion: v1
kind: Secret
metadata:
  name: floci-aws-creds
  namespace: platform-system
type: Opaque
stringData:
  access-key-id: test
  secret-access-key: test
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: floci-aws-creds
            namespace: platform-system
            key: access-key-id
          secretAccessKeySecretRef:
            name: floci-aws-creds
            namespace: platform-system
            key: secret-access-key
