apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: prod environment workloads (managed by the prod cluster's own Argo CD).
  sourceRepos:
    - http://172.18.255.209:3000/gitops/platform-config.git
    - http://172.18.255.209:3000/gitops/gitops-apps.git
    - http://172.18.255.209:3000/gitops/modular-monolithic-app.git
    - https://charts.external-secrets.io
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
